# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Fri Jul 31 22:04:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FlyApp(object):
    def setupUi(self, FlyApp):
        FlyApp.setObjectName("FlyApp")
        FlyApp.resize(800, 650)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlyApp.sizePolicy().hasHeightForWidth())
        FlyApp.setSizePolicy(sizePolicy)
        FlyApp.setMinimumSize(QtCore.QSize(800, 650))
        FlyApp.setMaximumSize(QtCore.QSize(800, 650))
        self.centralwidget = QtGui.QWidget(FlyApp)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Logo_lbl = QtGui.QLabel(self.centralwidget)
        self.Logo_lbl.setMaximumSize(QtCore.QSize(16777215, 240))
        self.Logo_lbl.setObjectName("Logo_lbl")
        self.horizontalLayout.addWidget(self.Logo_lbl)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gameSetting_gb = QtGui.QGroupBox(self.centralwidget)
        self.gameSetting_gb.setObjectName("gameSetting_gb")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gameSetting_gb)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gameFieldCellCapacity_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameFieldCellCapacity_lbl.setObjectName("gameFieldCellCapacity_lbl")
        self.gridLayout.addWidget(self.gameFieldCellCapacity_lbl, 1, 0, 1, 1)
        self.gameFieldCellCount_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameFieldCellCount_lbl.setObjectName("gameFieldCellCount_lbl")
        self.gridLayout.addWidget(self.gameFieldCellCount_lbl, 0, 0, 1, 1)
        self.flySpeed_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flySpeed_sb.sizePolicy().hasHeightForWidth())
        self.flySpeed_sb.setSizePolicy(sizePolicy)
        self.flySpeed_sb.setMinimum(1)
        self.flySpeed_sb.setMaximum(10)
        self.flySpeed_sb.setProperty("value", 3)
        self.flySpeed_sb.setObjectName("flySpeed_sb")
        self.gridLayout.addWidget(self.flySpeed_sb, 6, 1, 1, 2)
        self.gameSpeed_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameSpeed_lbl.setObjectName("gameSpeed_lbl")
        self.gridLayout.addWidget(self.gameSpeed_lbl, 7, 0, 1, 1)
        self.gameFieldCellCapacity_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFieldCellCapacity_sb.sizePolicy().hasHeightForWidth())
        self.gameFieldCellCapacity_sb.setSizePolicy(sizePolicy)
        self.gameFieldCellCapacity_sb.setMinimum(1)
        self.gameFieldCellCapacity_sb.setMaximum(99)
        self.gameFieldCellCapacity_sb.setProperty("value", 3)
        self.gameFieldCellCapacity_sb.setObjectName("gameFieldCellCapacity_sb")
        self.gridLayout.addWidget(self.gameFieldCellCapacity_sb, 1, 1, 1, 2)
        self.flyStandingDurationMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyStandingDurationMax_sb.setMinimum(100)
        self.flyStandingDurationMax_sb.setMaximum(9999)
        self.flyStandingDurationMax_sb.setSingleStep(100)
        self.flyStandingDurationMax_sb.setProperty("value", 3000)
        self.flyStandingDurationMax_sb.setObjectName("flyStandingDurationMax_sb")
        self.gridLayout.addWidget(self.flyStandingDurationMax_sb, 5, 2, 1, 1)
        self.flySpeed_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flySpeed_lbl.setObjectName("flySpeed_lbl")
        self.gridLayout.addWidget(self.flySpeed_lbl, 6, 0, 1, 1)
        self.flyWalkingDuration_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyWalkingDuration_lbl.setObjectName("flyWalkingDuration_lbl")
        self.gridLayout.addWidget(self.flyWalkingDuration_lbl, 4, 0, 1, 1)
        self.flyStupidityMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyStupidityMin_sb.sizePolicy().hasHeightForWidth())
        self.flyStupidityMin_sb.setSizePolicy(sizePolicy)
        self.flyStupidityMin_sb.setMinimum(100)
        self.flyStupidityMin_sb.setMaximum(9999)
        self.flyStupidityMin_sb.setSingleStep(100)
        self.flyStupidityMin_sb.setProperty("value", 3000)
        self.flyStupidityMin_sb.setObjectName("flyStupidityMin_sb")
        self.gridLayout.addWidget(self.flyStupidityMin_sb, 3, 1, 1, 1)
        self.flyStupidityMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyStupidityMax_sb.sizePolicy().hasHeightForWidth())
        self.flyStupidityMax_sb.setSizePolicy(sizePolicy)
        self.flyStupidityMax_sb.setMinimum(100)
        self.flyStupidityMax_sb.setMaximum(9999)
        self.flyStupidityMax_sb.setSingleStep(10)
        self.flyStupidityMax_sb.setProperty("value", 6000)
        self.flyStupidityMax_sb.setObjectName("flyStupidityMax_sb")
        self.gridLayout.addWidget(self.flyStupidityMax_sb, 3, 2, 1, 1)
        self.flyStupidity_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyStupidity_lbl.setObjectName("flyStupidity_lbl")
        self.gridLayout.addWidget(self.flyStupidity_lbl, 3, 0, 1, 1)
        self.flyWalkingDurationMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyWalkingDurationMin_sb.setMinimum(100)
        self.flyWalkingDurationMin_sb.setMaximum(9999)
        self.flyWalkingDurationMin_sb.setSingleStep(100)
        self.flyWalkingDurationMin_sb.setProperty("value", 1000)
        self.flyWalkingDurationMin_sb.setObjectName("flyWalkingDurationMin_sb")
        self.gridLayout.addWidget(self.flyWalkingDurationMin_sb, 4, 1, 1, 1)
        self.gameFieldCellCount_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFieldCellCount_sb.sizePolicy().hasHeightForWidth())
        self.gameFieldCellCount_sb.setSizePolicy(sizePolicy)
        self.gameFieldCellCount_sb.setMinimum(1)
        self.gameFieldCellCount_sb.setMaximum(8)
        self.gameFieldCellCount_sb.setProperty("value", 4)
        self.gameFieldCellCount_sb.setObjectName("gameFieldCellCount_sb")
        self.gridLayout.addWidget(self.gameFieldCellCount_sb, 0, 1, 1, 2)
        self.flyStandingDuration_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyStandingDuration_lbl.setObjectName("flyStandingDuration_lbl")
        self.gridLayout.addWidget(self.flyStandingDuration_lbl, 5, 0, 1, 1)
        self.flyWalkingDurationMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyWalkingDurationMax_sb.setMinimum(100)
        self.flyWalkingDurationMax_sb.setMaximum(9999)
        self.flyWalkingDurationMax_sb.setSingleStep(100)
        self.flyWalkingDurationMax_sb.setProperty("value", 3000)
        self.flyWalkingDurationMax_sb.setObjectName("flyWalkingDurationMax_sb")
        self.gridLayout.addWidget(self.flyWalkingDurationMax_sb, 4, 2, 1, 1)
        self.flyLifeCoefficient_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyLifeCoefficient_lbl.setObjectName("flyLifeCoefficient_lbl")
        self.gridLayout.addWidget(self.flyLifeCoefficient_lbl, 2, 0, 1, 1)
        self.gameSpeed_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.gameSpeed_sb.setMinimum(2)
        self.gameSpeed_sb.setMaximum(12)
        self.gameSpeed_sb.setSingleStep(1)
        self.gameSpeed_sb.setProperty("value", 4)
        self.gameSpeed_sb.setObjectName("gameSpeed_sb")
        self.gridLayout.addWidget(self.gameSpeed_sb, 7, 1, 1, 2)
        self.flyLifeCoefficient_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyLifeCoefficient_sb.setMinimum(1)
        self.flyLifeCoefficient_sb.setMaximum(99)
        self.flyLifeCoefficient_sb.setProperty("value", 4)
        self.flyLifeCoefficient_sb.setObjectName("flyLifeCoefficient_sb")
        self.gridLayout.addWidget(self.flyLifeCoefficient_sb, 2, 1, 1, 2)
        self.flyStandingDurationMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyStandingDurationMin_sb.setMinimum(100)
        self.flyStandingDurationMin_sb.setMaximum(9999)
        self.flyStandingDurationMin_sb.setSingleStep(100)
        self.flyStandingDurationMin_sb.setProperty("value", 1000)
        self.flyStandingDurationMin_sb.setObjectName("flyStandingDurationMin_sb")
        self.gridLayout.addWidget(self.flyStandingDurationMin_sb, 5, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.startGame_btn = QtGui.QPushButton(self.gameSetting_gb)
        self.startGame_btn.setObjectName("startGame_btn")
        self.verticalLayout_2.addWidget(self.startGame_btn)
        self.verticalLayout.addWidget(self.gameSetting_gb)
        self.game_gb = QtGui.QGroupBox(self.centralwidget)
        self.game_gb.setObjectName("game_gb")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.game_gb)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gameField_lo = QtGui.QHBoxLayout()
        self.gameField_lo.setObjectName("gameField_lo")
        self.gameField_w = QtGui.QWidget(self.game_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameField_w.sizePolicy().hasHeightForWidth())
        self.gameField_w.setSizePolicy(sizePolicy)
        self.gameField_w.setMinimumSize(QtCore.QSize(0, 0))
        self.gameField_w.setObjectName("gameField_w")
        self.gameField_lo.addWidget(self.gameField_w)
        self.statScroll_scrl = QtGui.QScrollArea(self.game_gb)
        self.statScroll_scrl.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.statScroll_scrl.setWidgetResizable(True)
        self.statScroll_scrl.setObjectName("statScroll_scrl")
        self.statScrollContent = QtGui.QWidget()
        self.statScrollContent.setGeometry(QtCore.QRect(0, 0, 697, 133))
        self.statScrollContent.setObjectName("statScrollContent")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.statScrollContent)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stat_text = QtGui.QTextBrowser(self.statScrollContent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stat_text.sizePolicy().hasHeightForWidth())
        self.stat_text.setSizePolicy(sizePolicy)
        self.stat_text.setMinimumSize(QtCore.QSize(0, 0))
        self.stat_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stat_text.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stat_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stat_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stat_text.setOverwriteMode(False)
        self.stat_text.setObjectName("stat_text")
        self.verticalLayout_3.addWidget(self.stat_text)
        self.statScroll_scrl.setWidget(self.statScrollContent)
        self.gameField_lo.addWidget(self.statScroll_scrl)
        self.verticalLayout_4.addLayout(self.gameField_lo)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.gameButtons_lo = QtGui.QHBoxLayout()
        self.gameButtons_lo.setObjectName("gameButtons_lo")
        self.newGame_btn = QtGui.QPushButton(self.game_gb)
        self.newGame_btn.setObjectName("newGame_btn")
        self.gameButtons_lo.addWidget(self.newGame_btn)
        self.addFly_btn = QtGui.QPushButton(self.game_gb)
        self.addFly_btn.setObjectName("addFly_btn")
        self.gameButtons_lo.addWidget(self.addFly_btn)
        self.stopGame_btn = QtGui.QPushButton(self.game_gb)
        self.stopGame_btn.setEnabled(True)
        self.stopGame_btn.setObjectName("stopGame_btn")
        self.gameButtons_lo.addWidget(self.stopGame_btn)
        self.verticalLayout_4.addLayout(self.gameButtons_lo)
        self.verticalLayout.addWidget(self.game_gb)
        FlyApp.setCentralWidget(self.centralwidget)
        self.startGame_act = QtGui.QAction(FlyApp)
        self.startGame_act.setObjectName("startGame_act")
        self.appClose_act = QtGui.QAction(FlyApp)
        self.appClose_act.setObjectName("appClose_act")
        self.action = QtGui.QAction(FlyApp)
        self.action.setObjectName("action")

        self.retranslateUi(FlyApp)
        QtCore.QMetaObject.connectSlotsByName(FlyApp)
        FlyApp.setTabOrder(self.gameFieldCellCount_sb, self.gameFieldCellCapacity_sb)
        FlyApp.setTabOrder(self.gameFieldCellCapacity_sb, self.flyLifeCoefficient_sb)
        FlyApp.setTabOrder(self.flyLifeCoefficient_sb, self.flyStupidityMin_sb)
        FlyApp.setTabOrder(self.flyStupidityMin_sb, self.flyStupidityMax_sb)
        FlyApp.setTabOrder(self.flyStupidityMax_sb, self.flyWalkingDurationMin_sb)
        FlyApp.setTabOrder(self.flyWalkingDurationMin_sb, self.flyWalkingDurationMax_sb)
        FlyApp.setTabOrder(self.flyWalkingDurationMax_sb, self.flyStandingDurationMin_sb)
        FlyApp.setTabOrder(self.flyStandingDurationMin_sb, self.flyStandingDurationMax_sb)
        FlyApp.setTabOrder(self.flyStandingDurationMax_sb, self.flySpeed_sb)
        FlyApp.setTabOrder(self.flySpeed_sb, self.gameSpeed_sb)
        FlyApp.setTabOrder(self.gameSpeed_sb, self.startGame_btn)
        FlyApp.setTabOrder(self.startGame_btn, self.newGame_btn)
        FlyApp.setTabOrder(self.newGame_btn, self.addFly_btn)
        FlyApp.setTabOrder(self.addFly_btn, self.stopGame_btn)
        FlyApp.setTabOrder(self.stopGame_btn, self.statScroll_scrl)

    def retranslateUi(self, FlyApp):
        FlyApp.setWindowTitle(QtGui.QApplication.translate("FlyApp", "Мухоемкость", None, QtGui.QApplication.UnicodeUTF8))
        self.Logo_lbl.setText(QtGui.QApplication.translate("FlyApp", "Logo", None, QtGui.QApplication.UnicodeUTF8))
        self.gameSetting_gb.setTitle(QtGui.QApplication.translate("FlyApp", "Настройки игры", None, QtGui.QApplication.UnicodeUTF8))
        self.gameFieldCellCapacity_lbl.setText(QtGui.QApplication.translate("FlyApp", "Мухоемкость", None, QtGui.QApplication.UnicodeUTF8))
        self.gameFieldCellCount_lbl.setText(QtGui.QApplication.translate("FlyApp", "Размер поля", None, QtGui.QApplication.UnicodeUTF8))
        self.gameSpeed_lbl.setText(QtGui.QApplication.translate("FlyApp", "Скорость игры", None, QtGui.QApplication.UnicodeUTF8))
        self.flySpeed_lbl.setText(QtGui.QApplication.translate("FlyApp", "Скорость полета/позания (пикселей/мс)", None, QtGui.QApplication.UnicodeUTF8))
        self.flyWalkingDuration_lbl.setText(QtGui.QApplication.translate("FlyApp", "Длительность стадии ползания (мин/макс в мс)", None, QtGui.QApplication.UnicodeUTF8))
        self.flyStupidity_lbl.setText(QtGui.QApplication.translate("FlyApp", "Мухотупость (мин/макс в мс)", None, QtGui.QApplication.UnicodeUTF8))
        self.flyStandingDuration_lbl.setText(QtGui.QApplication.translate("FlyApp", "Длительность стадии стояния (мин/макс в мс)", None, QtGui.QApplication.UnicodeUTF8))
        self.flyLifeCoefficient_lbl.setText(QtGui.QApplication.translate("FlyApp", "Коэффициент жизнеспособности", None, QtGui.QApplication.UnicodeUTF8))
        self.startGame_btn.setText(QtGui.QApplication.translate("FlyApp", "Старт", None, QtGui.QApplication.UnicodeUTF8))
        self.game_gb.setTitle(QtGui.QApplication.translate("FlyApp", "Игра", None, QtGui.QApplication.UnicodeUTF8))
        self.newGame_btn.setText(QtGui.QApplication.translate("FlyApp", "Новая игра", None, QtGui.QApplication.UnicodeUTF8))
        self.addFly_btn.setText(QtGui.QApplication.translate("FlyApp", "Добавить муху", None, QtGui.QApplication.UnicodeUTF8))
        self.stopGame_btn.setText(QtGui.QApplication.translate("FlyApp", "Остановить", None, QtGui.QApplication.UnicodeUTF8))
        self.startGame_act.setText(QtGui.QApplication.translate("FlyApp", "New Game", None, QtGui.QApplication.UnicodeUTF8))
        self.appClose_act.setText(QtGui.QApplication.translate("FlyApp", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("FlyApp", "Мухоемкость", None, QtGui.QApplication.UnicodeUTF8))

