# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FlyApp(object):
    def setupUi(self, FlyApp):
        FlyApp.setObjectName(_fromUtf8("FlyApp"))
        FlyApp.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlyApp.sizePolicy().hasHeightForWidth())
        FlyApp.setSizePolicy(sizePolicy)
        FlyApp.setMinimumSize(QtCore.QSize(800, 600))
        FlyApp.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(FlyApp)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gameSetting_gb = QtGui.QGroupBox(self.centralwidget)
        self.gameSetting_gb.setObjectName(_fromUtf8("gameSetting_gb"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gameSetting_gb)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gameFieldCellCapacity_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameFieldCellCapacity_lbl.setObjectName(_fromUtf8("gameFieldCellCapacity_lbl"))
        self.gridLayout.addWidget(self.gameFieldCellCapacity_lbl, 1, 0, 1, 1)
        self.gameFieldCellCount_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameFieldCellCount_lbl.setObjectName(_fromUtf8("gameFieldCellCount_lbl"))
        self.gridLayout.addWidget(self.gameFieldCellCount_lbl, 0, 0, 1, 1)
        self.flySpeed_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flySpeed_sb.sizePolicy().hasHeightForWidth())
        self.flySpeed_sb.setSizePolicy(sizePolicy)
        self.flySpeed_sb.setMinimum(1)
        self.flySpeed_sb.setMaximum(10)
        self.flySpeed_sb.setProperty("value", 3)
        self.flySpeed_sb.setObjectName(_fromUtf8("flySpeed_sb"))
        self.gridLayout.addWidget(self.flySpeed_sb, 6, 1, 1, 2)
        self.gameSpeed_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameSpeed_lbl.setObjectName(_fromUtf8("gameSpeed_lbl"))
        self.gridLayout.addWidget(self.gameSpeed_lbl, 7, 0, 1, 1)
        self.flyStandingDurationMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyStandingDurationMin_sb.setMinimum(10)
        self.flyStandingDurationMin_sb.setMaximum(100)
        self.flyStandingDurationMin_sb.setProperty("value", 20)
        self.flyStandingDurationMin_sb.setObjectName(_fromUtf8("flyStandingDurationMin_sb"))
        self.gridLayout.addWidget(self.flyStandingDurationMin_sb, 5, 1, 1, 1)
        self.gameFieldCellCapacity_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFieldCellCapacity_sb.sizePolicy().hasHeightForWidth())
        self.gameFieldCellCapacity_sb.setSizePolicy(sizePolicy)
        self.gameFieldCellCapacity_sb.setMinimum(1)
        self.gameFieldCellCapacity_sb.setMaximum(10)
        self.gameFieldCellCapacity_sb.setProperty("value", 3)
        self.gameFieldCellCapacity_sb.setObjectName(_fromUtf8("gameFieldCellCapacity_sb"))
        self.gridLayout.addWidget(self.gameFieldCellCapacity_sb, 1, 1, 1, 2)
        self.flyStandingDurationMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyStandingDurationMax_sb.setMinimum(10)
        self.flyStandingDurationMax_sb.setMaximum(100)
        self.flyStandingDurationMax_sb.setProperty("value", 50)
        self.flyStandingDurationMax_sb.setObjectName(_fromUtf8("flyStandingDurationMax_sb"))
        self.gridLayout.addWidget(self.flyStandingDurationMax_sb, 5, 2, 1, 1)
        self.flySpeed_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flySpeed_lbl.setObjectName(_fromUtf8("flySpeed_lbl"))
        self.gridLayout.addWidget(self.flySpeed_lbl, 6, 0, 1, 1)
        self.flyWalkingDuration_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyWalkingDuration_lbl.setObjectName(_fromUtf8("flyWalkingDuration_lbl"))
        self.gridLayout.addWidget(self.flyWalkingDuration_lbl, 4, 0, 1, 1)
        self.flyStupidityMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyStupidityMin_sb.sizePolicy().hasHeightForWidth())
        self.flyStupidityMin_sb.setSizePolicy(sizePolicy)
        self.flyStupidityMin_sb.setMinimum(1)
        self.flyStupidityMin_sb.setMaximum(100)
        self.flyStupidityMin_sb.setProperty("value", 50)
        self.flyStupidityMin_sb.setObjectName(_fromUtf8("flyStupidityMin_sb"))
        self.gridLayout.addWidget(self.flyStupidityMin_sb, 3, 1, 1, 1)
        self.flyStupidityMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyStupidityMax_sb.sizePolicy().hasHeightForWidth())
        self.flyStupidityMax_sb.setSizePolicy(sizePolicy)
        self.flyStupidityMax_sb.setMinimum(1)
        self.flyStupidityMax_sb.setMaximum(100)
        self.flyStupidityMax_sb.setSingleStep(1)
        self.flyStupidityMax_sb.setProperty("value", 100)
        self.flyStupidityMax_sb.setObjectName(_fromUtf8("flyStupidityMax_sb"))
        self.gridLayout.addWidget(self.flyStupidityMax_sb, 3, 2, 1, 1)
        self.flyStupidity_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyStupidity_lbl.setObjectName(_fromUtf8("flyStupidity_lbl"))
        self.gridLayout.addWidget(self.flyStupidity_lbl, 3, 0, 1, 1)
        self.flyWalkingDurationMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyWalkingDurationMin_sb.setMinimum(10)
        self.flyWalkingDurationMin_sb.setMaximum(100)
        self.flyWalkingDurationMin_sb.setProperty("value", 20)
        self.flyWalkingDurationMin_sb.setObjectName(_fromUtf8("flyWalkingDurationMin_sb"))
        self.gridLayout.addWidget(self.flyWalkingDurationMin_sb, 4, 1, 1, 1)
        self.gameFieldCellCount_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFieldCellCount_sb.sizePolicy().hasHeightForWidth())
        self.gameFieldCellCount_sb.setSizePolicy(sizePolicy)
        self.gameFieldCellCount_sb.setMinimum(1)
        self.gameFieldCellCount_sb.setMaximum(10)
        self.gameFieldCellCount_sb.setProperty("value", 4)
        self.gameFieldCellCount_sb.setObjectName(_fromUtf8("gameFieldCellCount_sb"))
        self.gridLayout.addWidget(self.gameFieldCellCount_sb, 0, 1, 1, 2)
        self.flyStandingDuration_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyStandingDuration_lbl.setObjectName(_fromUtf8("flyStandingDuration_lbl"))
        self.gridLayout.addWidget(self.flyStandingDuration_lbl, 5, 0, 1, 1)
        self.flyWalkingDurationMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyWalkingDurationMax_sb.setMinimum(10)
        self.flyWalkingDurationMax_sb.setMaximum(100)
        self.flyWalkingDurationMax_sb.setProperty("value", 50)
        self.flyWalkingDurationMax_sb.setObjectName(_fromUtf8("flyWalkingDurationMax_sb"))
        self.gridLayout.addWidget(self.flyWalkingDurationMax_sb, 4, 2, 1, 1)
        self.gameSpeed_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.gameSpeed_sb.setMinimum(10)
        self.gameSpeed_sb.setMaximum(1000)
        self.gameSpeed_sb.setProperty("value", 24)
        self.gameSpeed_sb.setObjectName(_fromUtf8("gameSpeed_sb"))
        self.gridLayout.addWidget(self.gameSpeed_sb, 7, 1, 1, 2)
        self.flyLifeCoefficient_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyLifeCoefficient_lbl.setObjectName(_fromUtf8("flyLifeCoefficient_lbl"))
        self.gridLayout.addWidget(self.flyLifeCoefficient_lbl, 2, 0, 1, 1)
        self.flyLifeCoefficient_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyLifeCoefficient_sb.setMinimum(1)
        self.flyLifeCoefficient_sb.setMaximum(10)
        self.flyLifeCoefficient_sb.setProperty("value", 5)
        self.flyLifeCoefficient_sb.setObjectName(_fromUtf8("flyLifeCoefficient_sb"))
        self.gridLayout.addWidget(self.flyLifeCoefficient_sb, 2, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.gameSetting_gb)
        self.gameField_w = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameField_w.sizePolicy().hasHeightForWidth())
        self.gameField_w.setSizePolicy(sizePolicy)
        self.gameField_w.setObjectName(_fromUtf8("gameField_w"))
        self.verticalLayout.addWidget(self.gameField_w)
        self.startGame_btn = QtGui.QPushButton(self.centralwidget)
        self.startGame_btn.setObjectName(_fromUtf8("startGame_btn"))
        self.verticalLayout.addWidget(self.startGame_btn)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.addFly_btn = QtGui.QPushButton(self.centralwidget)
        self.addFly_btn.setObjectName(_fromUtf8("addFly_btn"))
        self.horizontalLayout.addWidget(self.addFly_btn)
        self.stopGame_btn = QtGui.QPushButton(self.centralwidget)
        self.stopGame_btn.setEnabled(True)
        self.stopGame_btn.setObjectName(_fromUtf8("stopGame_btn"))
        self.horizontalLayout.addWidget(self.stopGame_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        FlyApp.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FlyApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        FlyApp.setMenuBar(self.menubar)
        self.actionNewGame = QtGui.QAction(FlyApp)
        self.actionNewGame.setObjectName(_fromUtf8("actionNewGame"))
        self.actionExit = QtGui.QAction(FlyApp)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNewGame)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(FlyApp)
        QtCore.QMetaObject.connectSlotsByName(FlyApp)

    def retranslateUi(self, FlyApp):
        FlyApp.setWindowTitle(_translate("FlyApp", "Мухоемкость", None))
        self.gameSetting_gb.setTitle(_translate("FlyApp", "Настройки игры", None))
        self.gameFieldCellCapacity_lbl.setText(_translate("FlyApp", "Мухоемкость", None))
        self.gameFieldCellCount_lbl.setText(_translate("FlyApp", "Размер поля", None))
        self.gameSpeed_lbl.setText(_translate("FlyApp", "Скорость игры (кадров в секунду)", None))
        self.flySpeed_lbl.setText(_translate("FlyApp", "Скорость полета/позания", None))
        self.flyWalkingDuration_lbl.setText(_translate("FlyApp", "Длительность стадии ползания (мин/макс)", None))
        self.flyStupidity_lbl.setText(_translate("FlyApp", "Мухотупость (мин/макс)", None))
        self.flyStandingDuration_lbl.setText(_translate("FlyApp", "Длительность стадии стояния (мин/макс)", None))
        self.flyLifeCoefficient_lbl.setText(_translate("FlyApp", "Коэффициент жизнеспособности", None))
        self.startGame_btn.setText(_translate("FlyApp", "Старт", None))
        self.addFly_btn.setText(_translate("FlyApp", "Добавить муху", None))
        self.stopGame_btn.setText(_translate("FlyApp", "Стоп", None))
        self.menuFile.setTitle(_translate("FlyApp", "Файл", None))
        self.menuAbout.setTitle(_translate("FlyApp", "О программе", None))
        self.actionNewGame.setText(_translate("FlyApp", "New Game", None))
        self.actionExit.setText(_translate("FlyApp", "Exit", None))

