# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Fri Jul 31 13:59:07 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FlyApp(object):
    def setupUi(self, FlyApp):
        FlyApp.setObjectName("FlyApp")
        FlyApp.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlyApp.sizePolicy().hasHeightForWidth())
        FlyApp.setSizePolicy(sizePolicy)
        FlyApp.setMinimumSize(QtCore.QSize(800, 600))
        FlyApp.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(FlyApp)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gameSetting_gb = QtGui.QGroupBox(self.centralwidget)
        self.gameSetting_gb.setObjectName("gameSetting_gb")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gameSetting_gb)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gameFieldCellCapacity_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameFieldCellCapacity_lbl.setObjectName("gameFieldCellCapacity_lbl")
        self.gridLayout.addWidget(self.gameFieldCellCapacity_lbl, 1, 0, 1, 1)
        self.gameFieldCellCount_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameFieldCellCount_lbl.setObjectName("gameFieldCellCount_lbl")
        self.gridLayout.addWidget(self.gameFieldCellCount_lbl, 0, 0, 1, 1)
        self.flySpeed_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flySpeed_sb.sizePolicy().hasHeightForWidth())
        self.flySpeed_sb.setSizePolicy(sizePolicy)
        self.flySpeed_sb.setMinimum(1)
        self.flySpeed_sb.setMaximum(10)
        self.flySpeed_sb.setProperty("value", 3)
        self.flySpeed_sb.setObjectName("flySpeed_sb")
        self.gridLayout.addWidget(self.flySpeed_sb, 6, 1, 1, 2)
        self.gameSpeed_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameSpeed_lbl.setObjectName("gameSpeed_lbl")
        self.gridLayout.addWidget(self.gameSpeed_lbl, 7, 0, 1, 1)
        self.flyStandingDurationMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyStandingDurationMin_sb.setMinimum(10)
        self.flyStandingDurationMin_sb.setMaximum(100)
        self.flyStandingDurationMin_sb.setProperty("value", 20)
        self.flyStandingDurationMin_sb.setObjectName("flyStandingDurationMin_sb")
        self.gridLayout.addWidget(self.flyStandingDurationMin_sb, 5, 1, 1, 1)
        self.gameFieldCellCapacity_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFieldCellCapacity_sb.sizePolicy().hasHeightForWidth())
        self.gameFieldCellCapacity_sb.setSizePolicy(sizePolicy)
        self.gameFieldCellCapacity_sb.setMinimum(1)
        self.gameFieldCellCapacity_sb.setMaximum(10)
        self.gameFieldCellCapacity_sb.setProperty("value", 3)
        self.gameFieldCellCapacity_sb.setObjectName("gameFieldCellCapacity_sb")
        self.gridLayout.addWidget(self.gameFieldCellCapacity_sb, 1, 1, 1, 2)
        self.flyStandingDurationMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyStandingDurationMax_sb.setMinimum(10)
        self.flyStandingDurationMax_sb.setMaximum(100)
        self.flyStandingDurationMax_sb.setProperty("value", 50)
        self.flyStandingDurationMax_sb.setObjectName("flyStandingDurationMax_sb")
        self.gridLayout.addWidget(self.flyStandingDurationMax_sb, 5, 2, 1, 1)
        self.flySpeed_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flySpeed_lbl.setObjectName("flySpeed_lbl")
        self.gridLayout.addWidget(self.flySpeed_lbl, 6, 0, 1, 1)
        self.flyWalkingDuration_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyWalkingDuration_lbl.setObjectName("flyWalkingDuration_lbl")
        self.gridLayout.addWidget(self.flyWalkingDuration_lbl, 4, 0, 1, 1)
        self.flyStupidityMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyStupidityMin_sb.sizePolicy().hasHeightForWidth())
        self.flyStupidityMin_sb.setSizePolicy(sizePolicy)
        self.flyStupidityMin_sb.setMinimum(1)
        self.flyStupidityMin_sb.setMaximum(100)
        self.flyStupidityMin_sb.setProperty("value", 50)
        self.flyStupidityMin_sb.setObjectName("flyStupidityMin_sb")
        self.gridLayout.addWidget(self.flyStupidityMin_sb, 3, 1, 1, 1)
        self.flyStupidityMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyStupidityMax_sb.sizePolicy().hasHeightForWidth())
        self.flyStupidityMax_sb.setSizePolicy(sizePolicy)
        self.flyStupidityMax_sb.setMinimum(1)
        self.flyStupidityMax_sb.setMaximum(100)
        self.flyStupidityMax_sb.setSingleStep(1)
        self.flyStupidityMax_sb.setProperty("value", 100)
        self.flyStupidityMax_sb.setObjectName("flyStupidityMax_sb")
        self.gridLayout.addWidget(self.flyStupidityMax_sb, 3, 2, 1, 1)
        self.flyStupidity_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyStupidity_lbl.setObjectName("flyStupidity_lbl")
        self.gridLayout.addWidget(self.flyStupidity_lbl, 3, 0, 1, 1)
        self.flyWalkingDurationMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyWalkingDurationMin_sb.setMinimum(10)
        self.flyWalkingDurationMin_sb.setMaximum(100)
        self.flyWalkingDurationMin_sb.setProperty("value", 20)
        self.flyWalkingDurationMin_sb.setObjectName("flyWalkingDurationMin_sb")
        self.gridLayout.addWidget(self.flyWalkingDurationMin_sb, 4, 1, 1, 1)
        self.gameFieldCellCount_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFieldCellCount_sb.sizePolicy().hasHeightForWidth())
        self.gameFieldCellCount_sb.setSizePolicy(sizePolicy)
        self.gameFieldCellCount_sb.setMinimum(1)
        self.gameFieldCellCount_sb.setMaximum(10)
        self.gameFieldCellCount_sb.setProperty("value", 4)
        self.gameFieldCellCount_sb.setObjectName("gameFieldCellCount_sb")
        self.gridLayout.addWidget(self.gameFieldCellCount_sb, 0, 1, 1, 2)
        self.flyStandingDuration_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyStandingDuration_lbl.setObjectName("flyStandingDuration_lbl")
        self.gridLayout.addWidget(self.flyStandingDuration_lbl, 5, 0, 1, 1)
        self.flyWalkingDurationMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyWalkingDurationMax_sb.setMinimum(10)
        self.flyWalkingDurationMax_sb.setMaximum(100)
        self.flyWalkingDurationMax_sb.setProperty("value", 50)
        self.flyWalkingDurationMax_sb.setObjectName("flyWalkingDurationMax_sb")
        self.gridLayout.addWidget(self.flyWalkingDurationMax_sb, 4, 2, 1, 1)
        self.gameSpeed_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.gameSpeed_sb.setMinimum(10)
        self.gameSpeed_sb.setMaximum(1000)
        self.gameSpeed_sb.setProperty("value", 24)
        self.gameSpeed_sb.setObjectName("gameSpeed_sb")
        self.gridLayout.addWidget(self.gameSpeed_sb, 7, 1, 1, 2)
        self.flyLifeCoefficient_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyLifeCoefficient_lbl.setObjectName("flyLifeCoefficient_lbl")
        self.gridLayout.addWidget(self.flyLifeCoefficient_lbl, 2, 0, 1, 1)
        self.flyLifeCoefficient_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyLifeCoefficient_sb.setMinimum(1)
        self.flyLifeCoefficient_sb.setMaximum(10)
        self.flyLifeCoefficient_sb.setProperty("value", 5)
        self.flyLifeCoefficient_sb.setObjectName("flyLifeCoefficient_sb")
        self.gridLayout.addWidget(self.flyLifeCoefficient_sb, 2, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.gameSetting_gb)
        self.gameField_w = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameField_w.sizePolicy().hasHeightForWidth())
        self.gameField_w.setSizePolicy(sizePolicy)
        self.gameField_w.setObjectName("gameField_w")
        self.verticalLayout.addWidget(self.gameField_w)
        self.startGame_btn = QtGui.QPushButton(self.centralwidget)
        self.startGame_btn.setObjectName("startGame_btn")
        self.verticalLayout.addWidget(self.startGame_btn)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addFly_btn = QtGui.QPushButton(self.centralwidget)
        self.addFly_btn.setObjectName("addFly_btn")
        self.horizontalLayout.addWidget(self.addFly_btn)
        self.stopGame_btn = QtGui.QPushButton(self.centralwidget)
        self.stopGame_btn.setEnabled(True)
        self.stopGame_btn.setObjectName("stopGame_btn")
        self.horizontalLayout.addWidget(self.stopGame_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        FlyApp.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FlyApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        FlyApp.setMenuBar(self.menubar)
        self.actionNewGame = QtGui.QAction(FlyApp)
        self.actionNewGame.setObjectName("actionNewGame")
        self.actionExit = QtGui.QAction(FlyApp)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNewGame)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(FlyApp)
        QtCore.QMetaObject.connectSlotsByName(FlyApp)

    def retranslateUi(self, FlyApp):
        FlyApp.setWindowTitle(QtGui.QApplication.translate("FlyApp", "Мухоемкость", None, QtGui.QApplication.UnicodeUTF8))
        self.gameSetting_gb.setTitle(QtGui.QApplication.translate("FlyApp", "Настройки игры", None, QtGui.QApplication.UnicodeUTF8))
        self.gameFieldCellCapacity_lbl.setText(QtGui.QApplication.translate("FlyApp", "Мухоемкость", None, QtGui.QApplication.UnicodeUTF8))
        self.gameFieldCellCount_lbl.setText(QtGui.QApplication.translate("FlyApp", "Размер поля", None, QtGui.QApplication.UnicodeUTF8))
        self.gameSpeed_lbl.setText(QtGui.QApplication.translate("FlyApp", "Скорость игры (кадров в секунду)", None, QtGui.QApplication.UnicodeUTF8))
        self.flySpeed_lbl.setText(QtGui.QApplication.translate("FlyApp", "Скорость полета/позания", None, QtGui.QApplication.UnicodeUTF8))
        self.flyWalkingDuration_lbl.setText(QtGui.QApplication.translate("FlyApp", "Длительность стадии ползания (мин/макс)", None, QtGui.QApplication.UnicodeUTF8))
        self.flyStupidity_lbl.setText(QtGui.QApplication.translate("FlyApp", "Мухотупость (мин/макс)", None, QtGui.QApplication.UnicodeUTF8))
        self.flyStandingDuration_lbl.setText(QtGui.QApplication.translate("FlyApp", "Длительность стадии стояния (мин/макс)", None, QtGui.QApplication.UnicodeUTF8))
        self.flyLifeCoefficient_lbl.setText(QtGui.QApplication.translate("FlyApp", "Коэффициент жизнеспособности", None, QtGui.QApplication.UnicodeUTF8))
        self.startGame_btn.setText(QtGui.QApplication.translate("FlyApp", "Старт", None, QtGui.QApplication.UnicodeUTF8))
        self.addFly_btn.setText(QtGui.QApplication.translate("FlyApp", "Добавить муху", None, QtGui.QApplication.UnicodeUTF8))
        self.stopGame_btn.setText(QtGui.QApplication.translate("FlyApp", "Стоп", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("FlyApp", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("FlyApp", "О программе", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewGame.setText(QtGui.QApplication.translate("FlyApp", "New Game", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("FlyApp", "Exit", None, QtGui.QApplication.UnicodeUTF8))

