# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FlyApp(object):
    def setupUi(self, FlyApp):
        FlyApp.setObjectName(_fromUtf8("FlyApp"))
        FlyApp.resize(800, 650)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlyApp.sizePolicy().hasHeightForWidth())
        FlyApp.setSizePolicy(sizePolicy)
        FlyApp.setMinimumSize(QtCore.QSize(800, 650))
        FlyApp.setMaximumSize(QtCore.QSize(800, 650))
        self.centralwidget = QtGui.QWidget(FlyApp)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Logo_lbl = QtGui.QLabel(self.centralwidget)
        self.Logo_lbl.setMaximumSize(QtCore.QSize(16777215, 240))
        self.Logo_lbl.setObjectName(_fromUtf8("Logo_lbl"))
        self.horizontalLayout.addWidget(self.Logo_lbl)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gameSetting_gb = QtGui.QGroupBox(self.centralwidget)
        self.gameSetting_gb.setObjectName(_fromUtf8("gameSetting_gb"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gameSetting_gb)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gameFieldCellCapacity_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameFieldCellCapacity_lbl.setObjectName(_fromUtf8("gameFieldCellCapacity_lbl"))
        self.gridLayout.addWidget(self.gameFieldCellCapacity_lbl, 1, 0, 1, 1)
        self.gameFieldCellCount_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameFieldCellCount_lbl.setObjectName(_fromUtf8("gameFieldCellCount_lbl"))
        self.gridLayout.addWidget(self.gameFieldCellCount_lbl, 0, 0, 1, 1)
        self.flySpeed_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flySpeed_sb.sizePolicy().hasHeightForWidth())
        self.flySpeed_sb.setSizePolicy(sizePolicy)
        self.flySpeed_sb.setMinimum(1)
        self.flySpeed_sb.setMaximum(10)
        self.flySpeed_sb.setProperty("value", 3)
        self.flySpeed_sb.setObjectName(_fromUtf8("flySpeed_sb"))
        self.gridLayout.addWidget(self.flySpeed_sb, 6, 1, 1, 2)
        self.gameSpeed_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.gameSpeed_lbl.setObjectName(_fromUtf8("gameSpeed_lbl"))
        self.gridLayout.addWidget(self.gameSpeed_lbl, 7, 0, 1, 1)
        self.gameFieldCellCapacity_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFieldCellCapacity_sb.sizePolicy().hasHeightForWidth())
        self.gameFieldCellCapacity_sb.setSizePolicy(sizePolicy)
        self.gameFieldCellCapacity_sb.setMinimum(1)
        self.gameFieldCellCapacity_sb.setMaximum(99)
        self.gameFieldCellCapacity_sb.setProperty("value", 3)
        self.gameFieldCellCapacity_sb.setObjectName(_fromUtf8("gameFieldCellCapacity_sb"))
        self.gridLayout.addWidget(self.gameFieldCellCapacity_sb, 1, 1, 1, 2)
        self.flyStandingDurationMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyStandingDurationMax_sb.setMinimum(100)
        self.flyStandingDurationMax_sb.setMaximum(9999)
        self.flyStandingDurationMax_sb.setSingleStep(100)
        self.flyStandingDurationMax_sb.setProperty("value", 2000)
        self.flyStandingDurationMax_sb.setObjectName(_fromUtf8("flyStandingDurationMax_sb"))
        self.gridLayout.addWidget(self.flyStandingDurationMax_sb, 5, 2, 1, 1)
        self.flySpeed_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flySpeed_lbl.setObjectName(_fromUtf8("flySpeed_lbl"))
        self.gridLayout.addWidget(self.flySpeed_lbl, 6, 0, 1, 1)
        self.flyWalkingDuration_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyWalkingDuration_lbl.setObjectName(_fromUtf8("flyWalkingDuration_lbl"))
        self.gridLayout.addWidget(self.flyWalkingDuration_lbl, 4, 0, 1, 1)
        self.flyStupidityMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyStupidityMin_sb.sizePolicy().hasHeightForWidth())
        self.flyStupidityMin_sb.setSizePolicy(sizePolicy)
        self.flyStupidityMin_sb.setMinimum(100)
        self.flyStupidityMin_sb.setMaximum(9999)
        self.flyStupidityMin_sb.setSingleStep(100)
        self.flyStupidityMin_sb.setProperty("value", 3000)
        self.flyStupidityMin_sb.setObjectName(_fromUtf8("flyStupidityMin_sb"))
        self.gridLayout.addWidget(self.flyStupidityMin_sb, 3, 1, 1, 1)
        self.flyStupidityMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyStupidityMax_sb.sizePolicy().hasHeightForWidth())
        self.flyStupidityMax_sb.setSizePolicy(sizePolicy)
        self.flyStupidityMax_sb.setMinimum(100)
        self.flyStupidityMax_sb.setMaximum(9999)
        self.flyStupidityMax_sb.setSingleStep(10)
        self.flyStupidityMax_sb.setProperty("value", 6000)
        self.flyStupidityMax_sb.setObjectName(_fromUtf8("flyStupidityMax_sb"))
        self.gridLayout.addWidget(self.flyStupidityMax_sb, 3, 2, 1, 1)
        self.flyStupidity_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyStupidity_lbl.setObjectName(_fromUtf8("flyStupidity_lbl"))
        self.gridLayout.addWidget(self.flyStupidity_lbl, 3, 0, 1, 1)
        self.flyWalkingDurationMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyWalkingDurationMin_sb.setMinimum(100)
        self.flyWalkingDurationMin_sb.setMaximum(9999)
        self.flyWalkingDurationMin_sb.setSingleStep(100)
        self.flyWalkingDurationMin_sb.setProperty("value", 1000)
        self.flyWalkingDurationMin_sb.setObjectName(_fromUtf8("flyWalkingDurationMin_sb"))
        self.gridLayout.addWidget(self.flyWalkingDurationMin_sb, 4, 1, 1, 1)
        self.gameFieldCellCount_sb = QtGui.QSpinBox(self.gameSetting_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFieldCellCount_sb.sizePolicy().hasHeightForWidth())
        self.gameFieldCellCount_sb.setSizePolicy(sizePolicy)
        self.gameFieldCellCount_sb.setMinimum(1)
        self.gameFieldCellCount_sb.setMaximum(8)
        self.gameFieldCellCount_sb.setProperty("value", 4)
        self.gameFieldCellCount_sb.setObjectName(_fromUtf8("gameFieldCellCount_sb"))
        self.gridLayout.addWidget(self.gameFieldCellCount_sb, 0, 1, 1, 2)
        self.flyStandingDuration_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyStandingDuration_lbl.setObjectName(_fromUtf8("flyStandingDuration_lbl"))
        self.gridLayout.addWidget(self.flyStandingDuration_lbl, 5, 0, 1, 1)
        self.flyWalkingDurationMax_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyWalkingDurationMax_sb.setMinimum(100)
        self.flyWalkingDurationMax_sb.setMaximum(9999)
        self.flyWalkingDurationMax_sb.setSingleStep(100)
        self.flyWalkingDurationMax_sb.setProperty("value", 3000)
        self.flyWalkingDurationMax_sb.setObjectName(_fromUtf8("flyWalkingDurationMax_sb"))
        self.gridLayout.addWidget(self.flyWalkingDurationMax_sb, 4, 2, 1, 1)
        self.flyLifeCoefficient_lbl = QtGui.QLabel(self.gameSetting_gb)
        self.flyLifeCoefficient_lbl.setObjectName(_fromUtf8("flyLifeCoefficient_lbl"))
        self.gridLayout.addWidget(self.flyLifeCoefficient_lbl, 2, 0, 1, 1)
        self.gameSpeed_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.gameSpeed_sb.setMinimum(2)
        self.gameSpeed_sb.setMaximum(12)
        self.gameSpeed_sb.setSingleStep(1)
        self.gameSpeed_sb.setProperty("value", 4)
        self.gameSpeed_sb.setObjectName(_fromUtf8("gameSpeed_sb"))
        self.gridLayout.addWidget(self.gameSpeed_sb, 7, 1, 1, 2)
        self.flyLifeCoefficient_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyLifeCoefficient_sb.setMinimum(1)
        self.flyLifeCoefficient_sb.setMaximum(99)
        self.flyLifeCoefficient_sb.setProperty("value", 4)
        self.flyLifeCoefficient_sb.setObjectName(_fromUtf8("flyLifeCoefficient_sb"))
        self.gridLayout.addWidget(self.flyLifeCoefficient_sb, 2, 1, 1, 2)
        self.flyStandingDurationMin_sb = QtGui.QSpinBox(self.gameSetting_gb)
        self.flyStandingDurationMin_sb.setMinimum(100)
        self.flyStandingDurationMin_sb.setMaximum(9999)
        self.flyStandingDurationMin_sb.setSingleStep(100)
        self.flyStandingDurationMin_sb.setProperty("value", 1000)
        self.flyStandingDurationMin_sb.setObjectName(_fromUtf8("flyStandingDurationMin_sb"))
        self.gridLayout.addWidget(self.flyStandingDurationMin_sb, 5, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.startGame_btn = QtGui.QPushButton(self.gameSetting_gb)
        self.startGame_btn.setObjectName(_fromUtf8("startGame_btn"))
        self.verticalLayout_2.addWidget(self.startGame_btn)
        self.verticalLayout.addWidget(self.gameSetting_gb)
        self.game_gb = QtGui.QGroupBox(self.centralwidget)
        self.game_gb.setObjectName(_fromUtf8("game_gb"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.game_gb)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gameField_lo = QtGui.QHBoxLayout()
        self.gameField_lo.setObjectName(_fromUtf8("gameField_lo"))
        self.gameField_w = QtGui.QWidget(self.game_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameField_w.sizePolicy().hasHeightForWidth())
        self.gameField_w.setSizePolicy(sizePolicy)
        self.gameField_w.setMinimumSize(QtCore.QSize(0, 0))
        self.gameField_w.setObjectName(_fromUtf8("gameField_w"))
        self.gameField_lo.addWidget(self.gameField_w)
        self.statScroll_scrl = QtGui.QScrollArea(self.game_gb)
        self.statScroll_scrl.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.statScroll_scrl.setWidgetResizable(True)
        self.statScroll_scrl.setObjectName(_fromUtf8("statScroll_scrl"))
        self.statScrollContent = QtGui.QWidget()
        self.statScrollContent.setGeometry(QtCore.QRect(0, 0, 707, 133))
        self.statScrollContent.setObjectName(_fromUtf8("statScrollContent"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.statScrollContent)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.stat_text = QtGui.QTextBrowser(self.statScrollContent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stat_text.sizePolicy().hasHeightForWidth())
        self.stat_text.setSizePolicy(sizePolicy)
        self.stat_text.setMinimumSize(QtCore.QSize(0, 0))
        self.stat_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stat_text.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stat_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stat_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stat_text.setOverwriteMode(False)
        self.stat_text.setObjectName(_fromUtf8("stat_text"))
        self.verticalLayout_3.addWidget(self.stat_text)
        self.statScroll_scrl.setWidget(self.statScrollContent)
        self.gameField_lo.addWidget(self.statScroll_scrl)
        self.verticalLayout_4.addLayout(self.gameField_lo)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.gameButtons_lo = QtGui.QHBoxLayout()
        self.gameButtons_lo.setObjectName(_fromUtf8("gameButtons_lo"))
        self.newGame_btn = QtGui.QPushButton(self.game_gb)
        self.newGame_btn.setObjectName(_fromUtf8("newGame_btn"))
        self.gameButtons_lo.addWidget(self.newGame_btn)
        self.addFly_btn = QtGui.QPushButton(self.game_gb)
        self.addFly_btn.setObjectName(_fromUtf8("addFly_btn"))
        self.gameButtons_lo.addWidget(self.addFly_btn)
        self.stopGame_btn = QtGui.QPushButton(self.game_gb)
        self.stopGame_btn.setEnabled(True)
        self.stopGame_btn.setObjectName(_fromUtf8("stopGame_btn"))
        self.gameButtons_lo.addWidget(self.stopGame_btn)
        self.verticalLayout_4.addLayout(self.gameButtons_lo)
        self.verticalLayout.addWidget(self.game_gb)
        FlyApp.setCentralWidget(self.centralwidget)
        self.startGame_act = QtGui.QAction(FlyApp)
        self.startGame_act.setObjectName(_fromUtf8("startGame_act"))
        self.appClose_act = QtGui.QAction(FlyApp)
        self.appClose_act.setObjectName(_fromUtf8("appClose_act"))
        self.action = QtGui.QAction(FlyApp)
        self.action.setObjectName(_fromUtf8("action"))

        self.retranslateUi(FlyApp)
        QtCore.QMetaObject.connectSlotsByName(FlyApp)
        FlyApp.setTabOrder(self.gameFieldCellCount_sb, self.gameFieldCellCapacity_sb)
        FlyApp.setTabOrder(self.gameFieldCellCapacity_sb, self.flyLifeCoefficient_sb)
        FlyApp.setTabOrder(self.flyLifeCoefficient_sb, self.flyStupidityMin_sb)
        FlyApp.setTabOrder(self.flyStupidityMin_sb, self.flyStupidityMax_sb)
        FlyApp.setTabOrder(self.flyStupidityMax_sb, self.flyWalkingDurationMin_sb)
        FlyApp.setTabOrder(self.flyWalkingDurationMin_sb, self.flyWalkingDurationMax_sb)
        FlyApp.setTabOrder(self.flyWalkingDurationMax_sb, self.flyStandingDurationMin_sb)
        FlyApp.setTabOrder(self.flyStandingDurationMin_sb, self.flyStandingDurationMax_sb)
        FlyApp.setTabOrder(self.flyStandingDurationMax_sb, self.flySpeed_sb)
        FlyApp.setTabOrder(self.flySpeed_sb, self.gameSpeed_sb)
        FlyApp.setTabOrder(self.gameSpeed_sb, self.startGame_btn)
        FlyApp.setTabOrder(self.startGame_btn, self.newGame_btn)
        FlyApp.setTabOrder(self.newGame_btn, self.addFly_btn)
        FlyApp.setTabOrder(self.addFly_btn, self.stopGame_btn)
        FlyApp.setTabOrder(self.stopGame_btn, self.statScroll_scrl)

    def retranslateUi(self, FlyApp):
        FlyApp.setWindowTitle(_translate("FlyApp", "Мухоемкость", None))
        self.Logo_lbl.setText(_translate("FlyApp", "Logo", None))
        self.gameSetting_gb.setTitle(_translate("FlyApp", "Настройки игры", None))
        self.gameFieldCellCapacity_lbl.setText(_translate("FlyApp", "Мухоемкость", None))
        self.gameFieldCellCount_lbl.setText(_translate("FlyApp", "Размер поля", None))
        self.gameSpeed_lbl.setText(_translate("FlyApp", "Скорость игры", None))
        self.flySpeed_lbl.setText(_translate("FlyApp", "Скорость полета/позания (пикселей/мс)", None))
        self.flyWalkingDuration_lbl.setText(_translate("FlyApp", "Длительность стадии ползания (мин/макс в мс)", None))
        self.flyStupidity_lbl.setText(_translate("FlyApp", "Мухотупость (мин/макс в мс)", None))
        self.flyStandingDuration_lbl.setText(_translate("FlyApp", "Длительность стадии стояния (мин/макс в мс)", None))
        self.flyLifeCoefficient_lbl.setText(_translate("FlyApp", "Коэффициент жизнеспособности", None))
        self.startGame_btn.setText(_translate("FlyApp", "Старт", None))
        self.game_gb.setTitle(_translate("FlyApp", "Игра", None))
        self.newGame_btn.setText(_translate("FlyApp", "Новая игра", None))
        self.addFly_btn.setText(_translate("FlyApp", "Добавить муху", None))
        self.stopGame_btn.setText(_translate("FlyApp", "Остановить", None))
        self.startGame_act.setText(_translate("FlyApp", "New Game", None))
        self.appClose_act.setText(_translate("FlyApp", "Exit", None))
        self.action.setText(_translate("FlyApp", "Мухоемкость", None))

